services:
  postgres:
    image: postgres:15
    container_name: vehicle_postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 00aa1122
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    # profiles: ["dev"]
    build:
      context: ./backend
      # dockerfile: Dockerfile.dev
    container_name: vehicle_backend
    environment:
      DATABASE_URL: "postgresql://postgres:00aa1122@postgres:5432/test"
    ports:
      - "4000:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma db push && npm run start:dev"

  # backend_prod:
  #   profiles: ["prod"]
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: vehicle_backend_prod
  #   restart: always
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:00aa1122@postgres:5432/test"
  #   ports:
  #     - "4000:3001"
  #   depends_on:
  #     - postgres
  #   command: sh -c "npx prisma migrate deploy && npm run start:prod"

  frontend:
    # profiles: ["dev"]
    build:
      context: ./frontend
      # dockerfile: Dockerfile.dev
    container_name: vehicle_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # frontend_prod:
  #   profiles: ["prod"]
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: vehicle_frontend_prod
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend_prod
  #   environment:
  #     - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000

volumes:
  pgdata:
